language: python
python:
  - "2.7"
  - "3.6"

env:
# command to install dependencies, requirements.txt should NOT include numpy

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest
