language: python
python:
  - "2.7"
  - "3.6"

install: pip install flake8

before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest
